name: Herobrine
main: com.steaks4uce.Herobrine.Herobrine
author: steaks4uce
version: 1.1
description: Hes watching... and waiting.
commands:
  hb:
    description: Spawns Herobrine near the player
    usage: /hb
